### PR TITLE
Add basic 3.13 support, various cleanups and version bumps

### LINKED ISSUE #36: Cannot import on 3.13, importlib.resources.read_text is removed
```
tests/test_flake8_trio.py:24: in <module>
    from hypothesmith import from_grammar, from_node
.tox/py313/lib/python3.13/site-packages/hypothesmith/__init__.py:3: in <module>
    from hypothesmith.cst import from_node
.tox/py313/lib/python3.13/site-packages/hypothesmith/cst.py:24: in <module>
    from .syntactic import ALLOWED_CHARS
.tox/py313/lib/python3.13/site-packages/hypothesmith/syntactic.py:7: in <module>
    from importlib.resources import read_text
E   ImportError: cannot import name 'read_text' from 'importlib.resources' (/usr/lib/python3.13/importlib/resources/__init__.py)
```

https://docs.python.org/3/library/importlib.resources.html#importlib.resources.read_text says calls to the method can be replaced by
```python
files(package).joinpath(resource).read_text(encoding=encoding)
```

This is the only blocker (I think) from testing flake8-trio with 3.13

### PR DESCRIPTION
**Pull request by jakkdl**
* fixes #36
* ~~drops support for 3.8~~
* now importable on 3.13
* parso does not support 3.13, so those tests are marked with xfail
* added 3.13-dev to CI
* expanded tox config so it's easier to specify what python version you want to test, while leaving all previous functionality intact
* specified `base_python` in the `deps` environment. The files were previously generated with 3.10, so left it at that, although it probably makes more sense to make that `3.9`.
* updated `deps/check.txt` and `deps/test.txt` (feels like there should be a `tox -e deps` call in CI to check they're up-to-date?)
* bumped actions/checkout and actions/setup-python to latest versions
* I did not formally specify 3.13 support in `setup.py`, but looking up parso now I guess hyposmith viability does not strictly depend on it having 3.13 support.
* bumped mypy minimum version ... but it seems it's disabled in tox anyway?

### CODE REVIEW

**Comment by thejcannon** [comment]
LGTM

> I'm not 100% sure why test (3.8) is expected

Where are you seeing that exactly?

**Comment by jakkdl** [comment]
2024-02-15T13:40:32,122900227+01:00

although I can't see it in https://github.com/Zac-HD/hypothesmith/pull/37/checks so it's probably just github being weird?

**Comment by thejcannon** [comment]
@Zac-HD can confirm but I suspect that's because the branch protection rules likely still reference that job name?

**Comment by Zac-HD** [comment]
Yep, but also [3.8 EOL isn't until October](https://devguide.python.org/versions/), and I'd prefer not to drop it before then.  `if sys.version_info[:2] ...` instead?

**Comment by Zac-HD** [comment]
Otherwise looks good - thanks @jakkdl!

**Comment by jakkdl** [comment]
> Yep, but also [3.8 EOL isn't until October](https://devguide.python.org/versions/), and I'd prefer not to drop it before then. `if sys.version_info[:2] ...` instead?

oops, brain going a bit too fast. Will do

**Review by Zac-HD — APPROVED** [review]
Thanks @jakkdl!

**Pull request merged**
